GET http://localhost:8080/account
email: memorivera1@gmail.com
password: P4$$W0rD123A5

###
GET http://localhost:8080/account
email: memoriverastephens@gmail.com
password: P4$$W0rD123A5

###
POST http://localhost:8080/account
Content-Type: application/json

    { 
        "id_account": 0,
        "name": "Luis Guillermo Rivera Stephens",
        "email": "memoriverastephens@gmail.com",
        "password": "P4$$W0rD123A",
        "isstarted": false,
        "department_fk": 1,
        "ispm": true
    }

###
DELETE http://localhost:8080/account
email: memoriverastephens@gmail.com
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ1NDgwOTcsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyBSaXZlcmEgU3RlcGhlbnMkMmEkMTAkeW5zTUpGS3RCNWI3WncyM0IzR0gyZWtoRzZTcXlNQkpSdXRqUkdXSjVpZmNtTC9jUklGb2UifQ.4VTr6d6gcIZ_QKY0q70EMMAvqz0t20gsbW8ydpT3924

###
PUT http://localhost:8080/account
email: memoriverastephens@gmail.com
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ1NjA1MzYsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyBSaXZlcmEgU3RlcGhlbnMkMmEkMTAkOWVSTkhEaEJ3MjFOVThNd2I4aTZXZVlKQVp6NTZZMUdYbDVZUnJKalR6bGlpREJ2RHpQVU8ifQ.ZQXOatErflUL0Zo9wIl0HGaJb9_IamOzUIxGWHm2P6Q

    {
        "password": "P4$$W0rD123A",
        "new_password": "P4$$W0rD123A5"
    }


###
POST http://localhost:8080/tickets
id:4
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjYwMjEwMTIsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyQyYSQxMCQzZm1zSUIwSU00MTl5T1hkbWJXblVPS240SUVxVFh3S0ptRmFpRzZqMUhxRlBBNHFDQ012NiJ9.L5fdxsdl31jFpXzQBz4zQdQ1cAH8mRUSehSGSUBhr6Q

{
    "id_ticket":0,
    "title":"Ticket de prueba",
    "t_description":"Esta es una descripción de prueba",
    "creation_date": "",
    "id_account": 0,
    "owner": "",
    "department": "FrontEnd",
    "status": "New Unassigned",
    "priority": "High"
}

###
GET http://localhost:8080/tickets/all
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjU3Mjk0ODQsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyBSaXZlcmEgU3RlcGhlbnMkMmEkMTAkOGJmZThjQ0c0NDhXUUw5SjZVYS9tZTh4OTVEN0xEbFRDaWdmakhaU3VLZy9hSWVJZXNHY08ifQ.YZOmXhmlxp0lBNAGIGRU7PFwCCTJlV7BO_unNlcZQ3E
id:2

###
GET http://localhost:8080/tickets/department/3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjU2ODMzOTgsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyBSaXZlcmEgU3RlcGhlbnMkMmEkMTAkOGJmZThjQ0c0NDhXUUw5SjZVYS9tZTh4OTVEN0xEbFRDaWdmakhaU3VLZy9hSWVJZXNHY08ifQ.7I8axKIP0CggXmUPCwdxB8sPrfBDPeZpBqRiMCLDEYs
id:2

###
GET http://localhost:8080/tickets/open
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjU2ODMzOTgsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyBSaXZlcmEgU3RlcGhlbnMkMmEkMTAkOGJmZThjQ0c0NDhXUUw5SjZVYS9tZTh4OTVEN0xEbFRDaWdmakhaU3VLZy9hSWVJZXNHY08ifQ.7I8axKIP0CggXmUPCwdxB8sPrfBDPeZpBqRiMCLDEYs
id:2

###
GET http://localhost:8080/tickets/closed
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjU2ODMzOTgsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyBSaXZlcmEgU3RlcGhlbnMkMmEkMTAkOGJmZThjQ0c0NDhXUUw5SjZVYS9tZTh4OTVEN0xEbFRDaWdmakhaU3VLZy9hSWVJZXNHY08ifQ.7I8axKIP0CggXmUPCwdxB8sPrfBDPeZpBqRiMCLDEYs
id:2

###
GET http://localhost:8080/tickets/owner
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjU3Mjk0ODQsIm5hbWUiOiJMdWlzIEd1aWxsZXJtbyBSaXZlcmEgU3RlcGhlbnMkMmEkMTAkOGJmZThjQ0c0NDhXUUw5SjZVYS9tZTh4OTVEN0xEbFRDaWdmakhaU3VLZy9hSWVJZXNHY08ifQ.YZOmXhmlxp0lBNAGIGRU7PFwCCTJlV7BO_unNlcZQ3E
id:2




